apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aws-load-balancer-controller.yaml
- ingress.yaml
configMapGenerator:
- name: cluster-parameters
  envs:
  - params.env
vars:
- name: CLUSTER_NAME
  objref:
    kind: ConfigMap
    name: cluster-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.CLUSTER_NAME
- name: AWS_ROLE_ARN
  objref:
    kind: ConfigMap
    name: cluster-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AWS_ROLE_ARN