apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- rbac.yaml
- deployment.yaml
configMapGenerator:
- name: harbor-parameters
  envs:
  - params.env
vars:
- name: HARBOR_CREDENTIALS
  objref:
    kind: ConfigMap
    name: harbor-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.HARBOR_CREDENTIALS
